name: CI Pipeline

on:
  pull_request:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build App (optional)
        run: npm run build

      - name: Upload Build (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next
